name: 'Read config'

description: 'Check and read config file'
inputs:
  config_file_path:
    description: 'Path of Xquare Config file'
    required: true
  environment:
    description: 'Environment classification for servers (prod/stag)' 
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Check and read config values
      id: read-config
      shell: bash
      env:
        CONFIG_FILE_PATH: ${{ inputs.config_file_path }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/check_config.sh
        $GITHUB_ACTION_PATH/check_config.sh