name: 'Xquare deployment'
author: 'Xquare'
branding:
  icon: 'x-square'
  color: 'Purple'

description: 'Tasks to deploy to xquare server'
inputs:
  service_name:
    description: 'Name of project'
    required: true
  service_type:
    description: 'Type of project (ex. be, fe)'
    required: true
  environment:
    description: 'Environment classification for servers (prod/stag)' 
    required: true
  config_file_path:
    description: 'Path of Xquare Config file'
    default: '.xquare/config.yaml'
  xquare_role_arn:
    description: 'Role arn to assume xquare credentials. If you want to distribute to Xquare, please contact administrator and check the value.'
    required: true
  gitops_deploy_token:
    description: 'GitOps deploy token to repository dispatch, set this as your `secrets.GITOPS_DEPLOY_TOKEN`' 
    required: true

runs:
  using: 'composite'
  steps:

    # - name: Check config values and set environment values
    #   id: config_script
    #   shell: bash
    #   run: $GITHUB_ACTION_PATH/config_script.sh

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.xquare_role_arn }}
        aws-region: ap-northeast-2

    - name: Step name
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids:
          CLOUD_CONFIG_USERNAME,xquare/cloud-config
          CLOUD_CONFIG_PASSWORD,xquare/cloud-config

    - name: Get the tag if exist
      id: get_tag
      shell: bash
      run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version_tag::$(echo $GITHUB_REF | cut -d / -f 3)
          else
            echo ::set-output name=version_tag::$(github.sha)
          fi
        
    - name: Publish to Registry If Taged
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ inputs.service_name }}-${{ inputs.service_type }}
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: ${{ steps.ecr.outputs.registry }}
        tags: ${{ steps.get_tag.outputs.version_tag }}
        buildargs: |
          CLOUD_CONFIG_USERNAME=${{ env.CLOUD_CONFIG_USERNAME }}
          CLOUD_CONFIG_PASSWORD=${{ env.CLOUD_CONFIG_PASSWORD }}
          PROFILE=${{ inputs.environment }}

    # - name: Check required config exists
    #   id: check-yaml
    #   run: $GITHUB_ACTION_PATH/check_config.sh
    #   shell: bash
    #   env:
    #     CONFIG_FILE_PATH: ${{ inputs.config_file_path }}
    #     TARGET_BANCH: ${{ GITHUB_REF#refs/heads/ }}
    #     GIT_URL: ${{ $GITHUB_SERVER_URL }}/${{ $GITHUB_REPOSITORY }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ inputs.gitops_deploy_token }}
        repository: team-xquare/xquare-gitops-repo
        event-type: update_image
        client-payload: |
          '{
            "ref" : "${{ github.ref }}", 
            "version" : "${{ steps.get_tag.outputs.version_tag }}",
            "service_name" : "${{ inputs.service_name }}",
            "service_type" : "${{ inputs.service_type }}",
            "environment" : "${{ inputs.environment }}"
          }'