name: 'Create xquare ecr if not exists'
author: 'Xquare'
branding:
  icon: 'Xquare'
  color: 'Purple'

description: 'Tasks to create xquare ecr if not exists'
inputs:
  repository_name:
    description: 'name of ecr repository'
    required: true
  service_name:
    description: 'Name of service' 
    required: true
  service_type:
    description: 'Type of service' 
    required: true
  environment:
    description: 'Environment classification for servers (prod/stag)' 
    required: true
  github_token:
    description: 'Github personal access token to repository dispatch' 
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Check if ECR repository exists
      id: check
      shell: bash
      run: |
        set +e
        aws ecr describe-repositories --repository-names ${{ inputs.repository_name }}
        exit_code=$?
        set -e
        if [ $exit_code -ne 0 ]; then
          echo "ecr_exists=false" >> $GITHUB_OUTPUT
        else
          echo "ecr_exists=true" >> $GITHUB_OUTPUT
        fi

    - name: Create ECR repository if not exists
      if: steps.check.outputs.ecr_exists == 'false'
      shell: bash
      run: |
        aws ecr create-repository --repository-name ${{ inputs.repository_name }}

    - name: Terraform Repository Dispatch if not exists
      if: steps.check.outputs.ecr_exists == 'false'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ inputs.github_token }}
        repository: team-xquare/xquare-infrastructure-global
        event-type: add_ecr
        client-payload: |
          {
            "repository_name" : "${{ inputs.repository_name }}",
            "service_name" : "${{ inputs.service_name }}",
            "service_type" : "${{ inputs.service_type }}",
            "environment" : "${{ inputs.environment }}"
          }